### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by btbytes** [jrfondren/mmc-get#1]
```
mmc-get git:(f501609)$ make install
mmc -s hlc.gc -O4 --intermodule-optimization --make mmcget && mv -fv mmcget mmc-get
** Error making `Mercury/int3s/mmcget.int3'.
mmcget.m:011: Syntax error at token 'for': operator or `.' expected.
Making Mercury/int3s/manager.int3
Making Mercury/int3s/package.int3
Making Mercury/int3s/ioextra.int3
make: *** [mmc-get] Error 1
```

This is on Mac OS X. I have mercury 14.01.1 installed.

**Comment by jrfondren** [comment]
Thanks, I noted this on the webpage but failed to mention it on github or in the README: to use a 14.01 compiler you'll need to check out a specific branch. The full build instructions are:

```
$ git clone https://github.com/jrfondren/mmc-get.git
$ cd mmc-get
$ git checkout 14.01-compat
$ make install
```

The 'inst' syntax has long since changed in the release-of-the-day builds.

**Comment by jrfondren** [comment]
updated README

**Comment by jrfondren** [comment]
actually, this still doesn't build on OSX due to environ.

**Comment by jrfondren** [comment]
that should be resolved now as well. I'd already run into this issue with getr.
